add config settings

diff --git a/devstack/lib/apmec b/devstack/lib/apmec
--- a/devstack/lib/apmec
+++ b/devstack/lib/apmec
@@ -38,10 +38,6 @@ set +o xtrace
 # Defaults
 # --------
 
-if is_ssl_enabled_service "apmec" || is_service_enabled tls-proxy; then
-    APMEC_PROTOCOL="https"
-fi
-
 # Set up default directories
 GITREPO["apmec-horizon"]=${APMECHORIZON_REPO:-${CUSTOM_BASE}/apmec-horizon.git}
 GITBRANCH["apmec-horizon"]=${APMECHORIZON_BRANCH:-apmec-refactor}
@@ -108,12 +104,6 @@ HEAT_CONF_DIR=/etc/heat
 
 # Functions
 # ---------
-# Test if any Apmec services are enabled
-# is_apmec_enabled
-function is_apmec_enabled {
-    [[ ,${ENABLED_SERVICES} =~ ,"apmec" ]] && return 0
-    return 1
-}
 
 # create_apmec_cache_dir() - Part of the _apmec_setup_keystone() process
 function create_apmec_cache_dir {
@@ -134,6 +124,7 @@ function create_apmec_accounts {
         create_service_user "apmec"
         get_or_create_role "advsvc"
         create_service_user "apmec" "advsvc"
+        create_service_user "apmec" "admin"
 
         local apmec_service=$(get_or_create_service "apmec" \
             "mec-orchestration" "Apmec MEC Orchestration Service")
@@ -165,26 +156,26 @@ function start_apmec {
     local cfg_file_options="--config-file $APMEC_CONF"
     local service_port=$APMEC_PORT
     local service_protocol=$APMEC_PROTOCOL
-    if is_service_enabled tls-proxy; then
-        service_port=$APMEC_PORT_INT
-        service_protocol="http"
-    fi
-    # Start apmec conductor
-    run_process apmec-conductor "$APMEC_BIN_DIR/apmec-conductor $cfg_file_options"
+
     # Start the Apmec service
-    run_process apmec "$APMEC_BIN_DIR/apmec-server $cfg_file_options"
+    sudo cp $APMEC_DIR/etc/systemd/system/apmec.service $SYSTEMD_DIR/devstack@apmec.service
+    iniset -sudo $SYSTEMD_DIR/devstack@apmec.service "Service" "User" $STACK_USER
+    iniset -sudo $SYSTEMD_DIR/devstack@apmec.service "Service" "ExecStart" "$APMEC_BIN_DIR/apmec-server $cfg_file_options"
+    sudo systemctl enable devstack@apmec.service
+    sudo systemctl restart devstack@apmec.service
+    # Start the Apmec conductor service
+    sudo cp $APMEC_DIR/etc/systemd/system/apmec-conductor.service $SYSTEMD_DIR/devstack@apmec-conductor.service
+    iniset -sudo $SYSTEMD_DIR/devstack@apmec-conductor.service "Service" "User" $STACK_USER
+    iniset -sudo $SYSTEMD_DIR/devstack@apmec-conductor.service "Service" "ExecStart" "$APMEC_BIN_DIR/apmec-conductor $cfg_file_options"
+    sudo systemctl enable devstack@apmec-conductor.service
+    sudo systemctl restart devstack@apmec-conductor.service
     echo "Waiting for Apmec to start..."
-    if is_ssl_enabled_service "apmec"; then
-        ssl_ca="--ca-certificate=${SSL_BUNDLE_FILE}"
-    fi
-    if ! timeout $SERVICE_TIMEOUT sh -c "while ! wget ${ssl_ca} --no-proxy -q -O- $service_protocol://$APMEC_HOST:$service_port; do sleep 1; done"; then
+    if ! timeout $SERVICE_TIMEOUT sh -c "while ! wget --no-proxy -q -O- $service_protocol://$APMEC_HOST:$service_port; do sleep 1; done"; then
         die $LINENO "Apmec did not start"
     fi
-    # Start proxy if enabled
-    if is_service_enabled tls-proxy; then
-        start_tls_proxy '*' $APMEC_PORT $APMEC_HOST $APMEC_PORT_INT &
-    fi
 }
+
+
 
 # stop_apmec() - Stop running processes (non-screen)
 function stop_apmec {
@@ -229,37 +220,18 @@ function configure_apmec {
         iniset $APMEC_CONF DEFAULT logging_context_format_string "%(asctime)s.%(msecs)03d %(levelname)s %(name)s [%(request_id)s %(user_name)s %(project_name)s] %(instance)s%(message)s"
     fi
 
-    if is_service_enabled tls-proxy; then
-        # Set the service port for a proxy to take the original
-        iniset $APMEC_CONF DEFAULT bind_port "$APMEC_PORT_INT"
-    fi
-
-    if is_ssl_enabled_service "apmec"; then
-        ensure_certificates APMEC
-
-        iniset $APMEC_CONF DEFAULT use_ssl True
-        iniset $APMEC_CONF DEFAULT ssl_cert_file "$APMEC_SSL_CERT"
-        iniset $APMEC_CONF DEFAULT ssl_key_file "$APMEC_SSL_KEY"
-    fi
-
     # server
     APMEC_API_PASTE_FILE=$APMEC_CONF_DIR/api-paste.ini
-    APMEC_POLICY_FILE=$APMEC_CONF_DIR/policy.json
 
     cp $APMEC_DIR/etc/apmec/api-paste.ini $APMEC_API_PASTE_FILE
-    cp $APMEC_DIR/etc/apmec/policy.json $APMEC_POLICY_FILE
-
-    # allow apmec user to administer apmec to match apmec account
-    sed -i 's/"context_is_admin":  "role:admin"/"context_is_admin":  "role:admin or user_name:apmec"/g' $APMEC_POLICY_FILE
 
     iniset $APMEC_CONF DEFAULT debug $ENABLE_DEBUG_LOG_LEVEL
-    iniset $APMEC_CONF DEFAULT policy_file $APMEC_POLICY_FILE
 
     iniset $APMEC_CONF DEFAULT auth_strategy $APMEC_AUTH_STRATEGY
     _apmec_setup_keystone $APMEC_CONF keystone_authtoken
 
-    if [[ "${APMEC_MODE}" == "all" ]]; then
-        iniset "/$Q_PLUGIN_CONF_FILE" ml2 extension_drivers port_security
+    
+    if [[ "${APMEC_MODE}" == "all" || "${IS_ZUUL_FT}" == "True" ]]; then
         iniset "/$Q_PLUGIN_CONF_FILE" ml2_type_flat flat_networks $PUBLIC_PHYSICAL_NETWORK,$MGMT_PHYS_NET
         iniset "/$Q_PLUGIN_CONF_FILE" ovs bridge_mappings $PUBLIC_PHYSICAL_NETWORK:$PUBLIC_BRIDGE,$MGMT_PHYS_NET:$BR_MGMT
 
@@ -268,7 +240,7 @@ function configure_apmec {
         iniset $APMEC_CONF alarm_auth username admin
         iniset $APMEC_CONF alarm_auth password "$ADMIN_PASSWORD"
         iniset $APMEC_CONF alarm_auth project_name admin
-        iniset $APMEC_CONF alarm_auth url http://$SERVICE_HOST:35357/v3
+        iniset $APMEC_CONF alarm_auth url http://$SERVICE_HOST:5000/v3
 
         echo "Creating bridge"
         sudo ovs-vsctl --may-exist add-br ${BR_MGMT}
@@ -327,7 +299,7 @@ function _apmec_setup_keystone {
     # Configures keystone for metadata_agent
     # metadata_agent needs auth_url to communicate with keystone
     if [[ "$use_auth_url" == "True" ]]; then
-        iniset $conf_file $section auth_url $KEYSTONE_SERVICE_URI/v2.0
+        iniset $conf_file $section auth_url $KEYSTONE_SERVICE_URI
     fi
 
     create_apmec_cache_dir
@@ -347,6 +319,9 @@ function apmec_horizon_install {
     git_clone_by_name "apmec-horizon"
     setup_dev_lib "apmec-horizon"
     sudo cp $DEST/apmec-horizon/apmec_horizon/enabled/* $DEST/horizon/openstack_dashboard/enabled/
+    # make sure NFV's dashboard static files get loaded when deploying
+    $PYTHON $DEST/apmec-horizon/manage.py collectstatic --noinput
+    echo yes | $PYTHON $DEST/apmec-horizon/manage.py compress
     restart_apache_server
 }
 
@@ -369,38 +344,50 @@ function openstack_image_create {
 
 function apmec_check_and_download_images {
     local image_url
-    image_url[0]='http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img'
-    image_url[1]='https://downloads.openwrt.org/chaos_calmer/15.05/x86/kvm_guest/openwrt-15.05-x86-kvm_guest-combined-ext4.img.gz'
+    image_url[0]="http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img"
+    # Customized image of OpenWRT 15.05.1 that can fix the continuously
+    # respawning OpenWRT-based VNFs.
+    image_url[1]="$APMEC_DIR/samples/images/openwrt-x86-kvm_guest-combined-ext4.img.gz"
 
-    local image_fname image_name glance_name gz_pattern
+    local image_fname image_name glance_name
+    local gz_pattern="\.gz$"
     local length=${#image_url[@]}
     local index=0
     while [ $index -lt $length ]
     do
         image_fname=`basename "${image_url[$index]}"`
         glance_name=${image_fname%.*}
-        if [[ $glance_name =~ 'openwrt' ]]; then
-            glance_name='OpenWRT'
+        if [[ $glance_name =~ "openwrt" ]]; then
+            glance_name="OpenWRT"
         fi
         image_name=`openstack image list | grep "$glance_name" | awk '{print $4}'`
         if [[ $image_name == "" ]]; then
             if [[ ! -f $FILES/$image_fname || "$(stat -c "%s" $FILES/$image_fname)" = "0" ]]; then
-                {
-                    wget --progress=dot:giga -c ${image_url[$index]} -O $FILES/$image_fname
-                    gz_pattern="\.gz$"
-                    if [[ $image_fname =~ $gz_pattern ]]; then
-                        new_image_fname=${image_fname%.*}
-                        gunzip -c $FILES/$image_fname > $FILES/$new_image_fname
-                        image_fname=$new_image_fname
-                    fi
-                    openstack_image_create $FILES/$image_fname $glance_name
-                }||{
-                    echo "ERROR: apmec image create for $image_fname failed"
-                    image_fname=$image_fname"*"
-                    sudo rm -rf $FILES/$image_fname
-                    exit 1
-                }
+                if [[ -f ${image_url[$index]} ]]; then
+                    cp ${image_url[$index]} $FILES/$image_fname
+                else
+                    {
+                        wget --progress=dot:giga -c ${image_url[$index]} -O $FILES/$image_fname
+                    }||{
+                        echo "WARNING: download image ${image_url[$index]} failed"
+                        index=$(($index+1))
+                        continue
+                    }
+                fi
+                if [[ $image_fname =~ $gz_pattern ]]; then
+                    new_image_fname=${image_fname%.*}
+                    gunzip -c $FILES/$image_fname > $FILES/$new_image_fname
+                    image_fname=$new_image_fname
+                fi
             fi
+            {
+                openstack_image_create $FILES/$image_fname $glance_name
+            }||{
+                echo "ERROR: apmec image create for $image_fname failed"
+                image_fname=$image_fname"*"
+                sudo rm -rf $FILES/$image_fname
+                exit 1
+            }
         fi
         index=$(($index+1))
     done
@@ -443,40 +430,45 @@ function apmec_register_default_vim {
     get_or_create_project $DEFAULT_VIM_PROJECT_NAME
     echo "Create MEC VIM user $DEFAULT_VIM_USER ..."
     get_or_create_user $DEFAULT_VIM_USER $DEFAULT_VIM_PASSWORD
-    get_or_add_user_project_role "admin" $DEFAULT_VIM_USER $DEFAULT_VIM_PROJECT_NAME
-    get_or_add_user_project_role "advsvc" $DEFAULT_VIM_USER $DEFAULT_VIM_PROJECT_NAME
+    get_or_add_user_project_role admin $DEFAULT_VIM_USER $DEFAULT_VIM_PROJECT_NAME
+    # get_or_add_user_project_role advsvc $DEFAULT_VIM_USER $DEFAULT_VIM_PROJECT_NAME
 
-    echo "Register default VIM ..."
-    mkdir -p $DATA_DIR/apmec
-    cp $APMEC_DIR/devstack/vim_config.yaml $DATA_DIR/apmec
-    VIM_CONFIG_FILE="$DATA_DIR/apmec/vim_config.yaml"
+    echo "Set register default VIM sh which is called by ansible role..."
+    cp $APMEC_DIR/devstack/vim_config.yaml $APMEC_DATA_DIR
+    VIM_CONFIG_FILE="$APMEC_DATA_DIR/vim_config.yaml"
     sed -e "s|^auth_url:.*$|auth_url: \'${KEYSTONE_SERVICE_URI}\'|" -i $VIM_CONFIG_FILE
     echo "The content of VIM config file $VIM_CONFIG_FILE :"
     cat $VIM_CONFIG_FILE
-    local default_vim_id
-    DEFAULT_VIM_NAME="VIM0"
 
-    old_project=$OS_PROJECT_NAME
-    old_user=$OS_USERNAME
-    $TOP_DIR/tools/create_userrc.sh -P -u $DEFAULT_VIM_USER -C $DEFAULT_VIM_PROJECT_NAME -p $DEFAULT_VIM_PASSWORD
-    echo "Switch environment openrc:"
-    echo $(cat $TOP_DIR/accrc/$DEFAULT_VIM_PROJECT_NAME/$DEFAULT_VIM_USER)
-    . $TOP_DIR/accrc/$DEFAULT_VIM_PROJECT_NAME/$DEFAULT_VIM_USER
+    echo "Set up target openstack vim resources ..."
+    openstack --os-cloud=devstack-admin quota set \
+              --class --instances -1 --cores -1 --ram -1 default
+    openstack --os-cloud=devstack-admin \
+              quota set --ports -1 $DEFAULT_VIM_PROJECT_NAME
 
-    default_vim_id=$(apmec vim-register --is-default --description "Default VIM" --config-file $VIM_CONFIG_FILE $DEFAULT_VIM_NAME -c id | grep id | awk '{print $4}')
-    echo "Default VIM registration done as $default_vim_id at $KEYSTONE_SERVICE_URI."
-    echo "Switch back to old environment openrc:"
-    echo $(cat $TOP_DIR/accrc/$old_project/$old_user)
-    . $TOP_DIR/accrc/$old_project/$old_user
+    openstack --os-region-name $REGION_NAME --os-project-name $DEFAULT_VIM_PROJECT_NAME \
+              --os-user-domain-id default --os-username $DEFAULT_VIM_USER \
+              --os-project-domain-id default --os-auth-url $KEYSTONE_SERVICE_URI \
+              --os-password $DEFAULT_VIM_PASSWORD keypair create userKey
 
-    echo "Update apmec/tests/etc/samples/local-vim.yaml for functional testing"
-    functional_vim_file="$APMEC_DIR/apmec/tests/etc/samples/local-vim.yaml"
-    sed -e "s|^auth_url:.*$|auth_url: \'${KEYSTONE_SERVICE_URI}\'|" -i $functional_vim_file
+    openstack --os-region-name $REGION_NAME --os-project-name $DEFAULT_VIM_PROJECT_NAME \
+          --os-user-domain-id default --os-username $DEFAULT_VIM_USER \
+          --os-project-domain-id default --os-auth-url $KEYSTONE_SERVICE_URI \
+          --os-password $DEFAULT_VIM_PASSWORD \
+          security group create \
+          --description "apmec functest security group" test_secgrp
+
+    openstack --os-region-name $REGION_NAME --os-project-name $DEFAULT_VIM_PROJECT_NAME \
+          --os-user-domain-id default --os-username $DEFAULT_VIM_USER \
+          --os-project-domain-id default --os-auth-url $KEYSTONE_SERVICE_URI \
+          --os-password $DEFAULT_VIM_PASSWORD \
+          security group rule create \
+          --ingress --protocol icmp test_secgrp
+    openstack --os-region-name $REGION_NAME --os-project-name $DEFAULT_VIM_PROJECT_NAME \
+          --os-user-domain-id default --os-username $DEFAULT_VIM_USER \
+          --os-project-domain-id default --os-auth-url $KEYSTONE_SERVICE_URI \
+          --os-password $DEFAULT_VIM_PASSWORD \
+          security group rule create \
+          --ingress --protocol tcp --dst-port 22 test_secgrp
 }
 
-function modify_heat_flavor_policy_rule {
-    local policy_file=$HEAT_CONF_DIR/policy.yaml
-    touch $policy_file
-    # Allow non-admin projects with 'admin' roles to create flavors in Heat
-    echo '"resource_types:OS::Nova::Flavor": "role:admin"' >> $policy_file
-}
